const actionType =  { 
  GET_ARTICLE_LIST_START:'GET_ARTICLE_LIST_START',
  GET_ARTICLE_LIST_LOADING:'GET_ARTICLE_LIST_LOADING',
  GET_ARTICLE_LIST_END:'GET_ARTICLE_LIST_END',
}

export default actionType